services:
  redis:
    image: redis:7-alpine
    container_name: ms-account-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: ms-account-redis-insight
    ports:
      - "8001:5540"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-data: