spring:
  application:
    name: ms-account
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms

core-banking:
  base-url: http://localhost:3001

cache:
  ttl:
    account-balance: 5m # Time To Live de los registros en Redis

resilience4j:
  ratelimiter:
    instances:
      backendService: # nombre lógico del RateLimiter
        limit-for-period: 2 # número máximo de llamadas permitidas por periodo
        limit-refresh-period: 50s # duración del periodo (ej: 1 segundo)
        timeout-duration: 2s # cuánto esperar para adquirir un permiso
        registerHealthIndicator: true # expone estado en actuator/health

management:
  health:
    redis:
      enabled: true
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, circuitbreakers, circuitbreakerevents, retryevents

server:
  port: 9092

logging:
  level:
    io.github.resilience4j.ratelimiter: DEBUG
